services:
  postgres:
    image: postgres:17
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eventhub-network

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      args:
        API_PORT: ${API_PORT:-3001}
    container_name: eventhub-app-api
    restart: always
    env_file: .env
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/eventhub
    networks:
      - eventhub-network
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        WEB_PORT: ${WEB_PORT:-3000}
    container_name: eventhub-app-web
    restart: always
    env_file: .env
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    networks:
      - eventhub-network
    depends_on:
      - api

volumes:
  postgres_data:

networks:
  eventhub-network:
    driver: bridge
