name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: eventhub_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma client
        run: |
          cd apps/api
          pnpm prisma generate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/eventhub_test

      - name: Run database migrations
        run: |
          cd apps/api
          pnpm prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/eventhub_test

      - name: Push Prisma schema
        run: |
          cd apps/api
          pnpm prisma db:push
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/eventhub_test

      - name: Seed database
        run: |
          cd apps/api
          pnpm db:seed
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/eventhub_test

      - name: Build projects
        run: pnpm build

      - name: Run API tests
        run: |
          cd apps/api
          pnpm test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/eventhub_test
          JWT_SECRET: test-secret
          JWT_REFRESH_SECRET: test-refresh-secret

      - name: Run E2E tests
        run: |
          cd apps/api
          pnpm test:e2e
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/eventhub_test
          JWT_SECRET: test-secret
          JWT_REFRESH_SECRET: test-refresh-secret

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Lint API
        run: |
          cd apps/api
          pnpm lint

      - name: Lint Web
        run: |
          cd apps/web
          pnpm lint

      - name: Type check
        run: |
          cd apps/web
          pnpm type-check
